### ISSUE TITLE
Hide Expression in repeat components

### ISSUE THREAD

**Issue by deexita** [ngx-formly/ngx-formly#1396]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```

**Current behavior**

We are having a repeater component in which each element should have an id. This component is visible based on some condition in hideExpression. If user has created some rows with some data , the form controls remains after the condition for hideExpression has been changed and data has been deleted from model. Now if user again change the condition to yes, All the old formcontrols are visible, but Id's are missing in the model.

**Expected behavior**

Deleting rows from the model should delete formgroups from array as well. Ids should be generated when user creates a new row.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-y4sgsy-8faeey

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
first I'd suggest upgrading into `V5` which solve several issues related to repeat type,
to take account of model changes you should make sure to override it also please note that
resetting model inside `hideExpression` is not recommended as it can produce some unexpected behavior you may try with `change` callback:
```ts
this.model = {
  ...this.model,
  investments: [],
};
```

for uuid I'd suggest using defaultValue (available since `V5`) see https://stackblitz.com/edit/angular-y4sgsy-tdbjkz?file=src/app/IdComponent.ts which will allow you to skip handling it in `RepeatTypeComponent`

https://stackblitz.com/edit/angular-y4sgsy-tdbjkz
