### ISSUE TITLE
Add and remove elements to fieldArray (repeat) programmatically from the component

### ISSUE THREAD

**Issue by Korbraan** [ngx-formly/ngx-formly#1676]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

I tried to use the [repeating section](https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section) example but I am stuck when I want to add new items to the fieldArray as the controls (buttons to add categories) are independent of the form, so I don't know how to use the FieldArrayType add and remove methods. 

**Expected behavior**

Being able to add and remove elements in a FieldArrayType programmatically (call the add and remove methods by hand in my component).
**Minimal reproduction of the problem with instructions**

Stackblitz: https://angular-jhvhvn.stackblitz.io

**Please tell us about your environment:** Fedora, VS Code, NPM
* **Angular version:** 7.2.0
* **Browser:** all 
* **Language:** all
* **Node (for AoT issues):** `node --version` = v10.15.1

Thank you in advance.

**Comment by aitboudad** [comment]
use one of the following ways:
1. update the model: https://stackblitz.com/edit/angular-jhvhvn-d6ozde
2. assign `add`/`remove` method to the `field` or `formState`: https://stackblitz.com/edit/angular-jhvhvn-4ykhtq

**Comment by eugeniopaguntalan** [comment]
Hi @aitboudad, I was trying to call templateOptions.add() unfortunately it's not accessible. :(

**Comment by aitboudad** [comment]
@eugeniopaguntalan fill a new issue with a reproduction example.

**Comment by YhEtesian** [comment]
Hello @aitboudad I'm using your [stackblitz](https://stackblitz.com/edit/angular-jhvhvn-d6ozde?file=src%2Fapp%2Fapp.component.ts)as an example to implement a fieldArray repeat. However I've run into a issue that seems to also be a problem in the stackblitz solution. In the stackblitz the fields have a className of 'col-sm-4', but they don't seem to enforce this. You can change the value around but the field will stay what seems to be col-12.

I have inspected the code with the chrome console and also changed the col-4-sm class in the console to col-2-sm, again nothing changes. Because of this whenever I use formArray the lay-out becomes huge because every field in the formArray takes up an entire line.

Is there a way to force the formly fields in a fieldArray to actually take the bootstrap class assigned to it?

**Comment by aitboudad** [comment]
@YhEtesian the bs grid require `formly-field` to be `display:block`, also the `row` class should be set using `fieldGroupClassName`:

// styles.scss
```scss
formly-field { display: block; }
```

// app.component.ts
```patch
fieldArray: {
+  fieldGroupClassName: 'row',
  ...
}
```

**Comment by YhEtesian** [comment]
Worked like a charm, thank you!
