### ISSUE TITLE
Kendo UI - Select multiple doesn't work

### ISSUE THREAD

**Issue by dalenguyen** [ngx-formly/ngx-formly#1685]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When clicking on Select Multiple, I cannot choose more than one option.

**Expected behavior**

When clicking on Select Multiple, I should be able to select more than one option.

**Minimal reproduction of the problem with instructions**

The behaviour can be reproduce here:
https://ngx-formly.github.io/ngx-formly/ui/kendo

**Please tell us about your environment:**

Chrome browser

**Comment by aitboudad** [comment]
kendo provide two separate components for `select` and `multiselect`, that's why we only support the first one. What I'd suggest is to create a custom field type named `multiselect`, luckily, I've done it for you this time :).
https://stackblitz.com/edit/angular-omczb8

if you want to learn more about custom field type check the following links:

- https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
- https://www.telerik.com/kendo-angular-ui/components/forms/integration-with-formly/

**Comment by dalenguyen** [comment]
Awesome, thanks @aitboudad  :)

**Comment by mikegoodstadt** [comment]
Hi @aitboudad - Am I correct that this is also the case for PrimeNg?
In the UI demo on formly.dev colapses the list before being able to select another.
The solution I presume is the same as that for Kendo ie. write a custom field...

**Comment by aitboudad** [comment]
@mikegoodstadt I think so, there is a pending PR for PrimeNg multi-select #2100, when time allows I may try to merge it as part of `5.6` version.
So I suggest creating a custom field type (check the PR source code) in the meantime.

**Comment by mikegoodstadt** [comment]
Thanks for making this clear and pointing to the PR - and thanks for this great Library!
