### ISSUE TITLE
Cross framework support for formly features as web component

### ISSUE THREAD

**Issue by rahulbhooteshwar** [ngx-formly/ngx-formly#1717]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**

Ngx-formly only works/targetted for Angular apps!
**Expected behavior**

It will be good if same thing can be used with cross framework support: Angular,React,Vue, No framework, Any Framework!!
Basically all formly functionalities made available as a web component via CDN script or npm module.

I
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I know other libraries to achieve things in Non Angular Apps but those are not mature like ngx formly!
Recently we required to create simillar automated forms in 2 of our app, one is Angular another is Vue/Nuxt.
For angular it was straight forward but for Vue we couldn’t use ngx formly for obvious reasons!
Then we came up with an idea. We created Angular element based module which used Ngx formly , compiled it & published it as ***web component*** script. Now we can include the same on any web page & use ngx- formly features irrespective of front end framework.

Limitation is that we only exposed things as props as per our requirements! If it can be implemented in generic fashion using angular elements, & officially comes from ngx formly community , this will be useful for everyone from non angular world!

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by rahulbhooteshwar** [comment]
@LalitKushwah please share the npm module and pkg link Of the generic wrapper we planned & created for our use case!!

**Comment by LalitKushwah** [comment]
@rahulbhooteshwar ,
Thanks for creating this feature request for the best support team I ever found. Yes, I can share.

https://www.npmjs.com/package/formly-wrapper-angular-element

@aitboudad 
Rahul and I have tried to create an [angular element](https://github.com/LalitKushwah/wrapper-formly) ( as a wrapper over ngx-formly module) for our need but it is not as mature as expected.

**Comment by aitboudad** [comment]
Hi,
Thanks for sharing your thoughts about that topic, I would say that one of my highest aims.
`formly` is such good lib which I think the other communities would benefit even though the `Angular` one is our main target for now.

`Angular` element appears a workaround to me if we want to go on the direction of wining the other communities we should try to speak their languages else its just a waste of time.
The process requires a quite amount of work (features/ support/ fixing bugs...) and due to the size of our team and leak of support (`$$`) it will be probably taken slowly but I'll try to provide a realistic roadmap for this.

if anyone wants to support my work on that part, I would be happy to make it my main task.

**Comment by rahulbhooteshwar** [comment]
@aitboudad , me & @LalitKushwah will love to work on the same. 

One more thought on the same...

If we want to support other communities & planning to do it from scratch, why don’t we go with web component way! We can leverage power of StencilJS to create the same & benefit all the web frameworks in one go!!

**Comment by aitboudad** [comment]
Starting from scratch would be a mistake, my plan is to do some refactoring in order to make angular forms an optional dependency. then we can start on adding other frameworks.

> If we want to support other communities & planning to do it from scratch, why don’t we go with web component way! We can leverage power of StencilJS to create the same & benefit all the web frameworks in one go!!

I'm not against web component at all, our approach in `formly` is to build the form on the top of form utilities that the framework provides but we'll see once starting on that part.
