### ISSUE TITLE
Question: why the formgroup data can't edit in one custom template

### ISSUE THREAD

**Issue by kevinfan35** [ngx-formly/ngx-formly#1745]
**I'm submitting a question**  (check one with "x")
```
 question on custom formly complate
```

**Current behavior**
My application based on formly, it works fine, then today i create a  new custom template for input label,  the UI displayed correctly and  the data echo in the input label, while when i tried to edit in the input label, error occurred and showed that can't assign to readonly property. So i checked the fromgroup property using Object.getOwnPropertyDescriptor(this.model, 'key'), the property is that writable: false, configurable: false, i didn't set these properties to false as it will cause this object become readonly  property.
Can anyone help me to solve this issue? i really don't why it occurs

**Expected behavior**
When i edit value, it should be editable and formgroup data will change 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by kevinfan35** [comment]
Issue desc: TypeError: cannot assign to read only property 'key' of object

**Comment by kevinfan35** [comment]
issue at js ngx-formly--core.js : 62  assignModelValue

**Comment by aitboudad** [comment]
can you provide a reproduction example using https://stackblitz.com/angular/dkyqrrbblvy

**Comment by RollsBean** [comment]
> can you provide a reproduction example using https://stackblitz.com/angular/dkyqrrbblvy

Hi aitboudad, it's hard to attach code to stackblitz, i debuged in local and found why model's properties can't edit, i use Router to redirect to another component and catch with query params, after redirect to destination component, i set model use taht:
`this.activatedRoute.queryParams.subscribe(params => {
      this.model = params;
    });`
i debuged Router source code, in Router, it will create a  object **ActivatedRouteSnapshot**
part of the source code
`snapshot = new ActivatedRouteSnapshot(consumedSegments, result.parameters, Object.freeze(__assign({}, this.urlTree.queryParams)), this.urlTree.fragment, getData(route), outlet, route.component, route, getSourceSegmentGroup(rawSegment), getPathIndexShift(rawSegment) + consumedSegments.length, getResolve(route));` 

**this.urlTree.queryParams** is the router params where this.model get reference, obviously, before ActivatedRouteSnapshot instance created, Router will freeze queryParams using Object.freeze(), that's the root cause that why i can't edit these values.

It's not formly issue, will enhance my code and test again, holp it make sense.

**Comment by aitboudad** [comment]
make sense!
