### ISSUE TITLE
Model is not clear in docs

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2003]
In the docs, it seems that model holds fields values as it appears in this example in the official docs
[https://formly.dev/guide/properties-options](https://formly.dev/guide/properties-options)

if so, why don't we use `value` in fieldsOptions?
if not, please provide a more clear explanation in your docs

**Comment by aitboudad** [comment]
The `model` represent the form `value` which can be retrieved from the Http call for example, when model is `undefined` we use the provided `defaultValue` from the field.
The purpose of `options` is to provide some extra behaviors which depend on the user's needs.

> if so, why don't we use value in fieldsOptions?

since the model does the same job, I don't see the needs for `value`.

**Comment by aitboudad** [comment]
> if not, please provide a more clear explanation in your docs

I would say PR welcomed 🙏 (https://github.com/ngx-formly/ngx-formly/tree/v5/demo/src/app/guides).

Right now we're focusing on `v6` which will provide a better doc for sure but it'll take more time to be ready.

**Comment by eng-dibo** [comment]
So it is better to change it's name to data. also make it optional, the docs says that is is a required field.

**Comment by aitboudad** [comment]
> the docs says that is is a required field.

`model` is required
