### ISSUE TITLE
(Ionic-angular 4) Number field returns string instead of number

### ISSUE THREAD

**Issue by sckumar** [ngx-formly/ngx-formly#2104]
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request

Current behavior

Input with type number set in template leads to return string.

Expected behavior

Input with type number set in template leads to returns numeric value.

Minimal reproduction of the problem with instructions

{ key: 'someKey', type: 'input', templateOptions: { type: 'number' } }

Output from form: "5"

Expected output: 5

UI: Ionic angular
Ionic version: 3
Angular version : 4.4.4
ngx-formly/core version : 3.1.0
ngx-formly/ionic version: 3.1.0

Upgraded to 
ngx-formly/core version : 4.8.2
ngx-formly/ionic version: 4.8.2

but not working still.

**Comment by aitboudad** [comment]
The issue has been fixed in `v5`, use one of the following solutions:

-  Update `Formly` version to the latest one (require ionic v5).
- or Create a custom field type `number`: https://formly.dev/guide/custom-formly-field
- or use `parsers` in a `number` type which extends input type through `NgModule`:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      types: [
        {
          name: 'number',
          extends: 'input',
          defaultOptions: {
            parsers: [Number],
            templateOptions: {
              type: 'number',
            }
          },
        },
      ],
    }),
})
export class AppModule { }
```

´´´ts
{ key: 'someKey', type: 'number' }
```
