### ISSUE TITLE
Support layout for Bootstrap Italia

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#2162]
[Bootstrap Italia](https://italia.github.io/bootstrap-italia/) is a package that follows the guideline for the web site of the Italian Public Administration. [ AGID ](https://www.agid.gov.it/en)

In this stackblitz I have added the package (`npm i bootstrap-italia --save`) but the layout still remaining the same.
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-uxtbrv

Example desiderated input form
https://italia.github.io/bootstrap-italia/docs/form/input/

The solution could be the customs template?

**Comment by raknjarasoa** [comment]
Hello,

The layout still remaining the same because you should @import bootstrap-italia in styles.scss or via cdn.
Precisely, the solution is the use of custom wrapper.
You can refer to existing one for bootstrap [here](https://github.com/ngx-formly/ngx-formly/blob/v5/src/bootstrap/src/lib/wrappers/form-field.wrapper.ts)
You can also find example usage [here](https://formly.dev/examples/other/nested-formly-forms)

**Comment by aitboudad** [comment]
import `bootstrap-italia` style and override the `form-field` wrapper if necessary.
