### ISSUE TITLE
In field select  show in value option this format `index: id` 

### ISSUE THREAD

**Issue by efaby** [ngx-formly/ngx-formly#2187]
**Description**
I need to get the value of a select but this field has created with this format index: id example 0: 1, then I caught this in change event this returned the value with this format and when I try to get the model value, this returned me value selected previously.

**Minimal Reproduction**
I caught this option in the documentation.

![Selection_016](https://user-images.githubusercontent.com/4182100/79702025-548d2500-8267-11ea-8507-2550fd3927db.png)

here in value option is `0: iron_man` and only should get me `iron_man`

https://stackblitz.com/edit/angular-ttbhu6

**Your Environment**

- Angular version: 9.1
- Formly version: 5.5.15

**Comment by aitboudad** [comment]
The value is handled by Angular through `[ngValue]` input, to get the expected value use `formControl.valueChanges` https://github.com/ngx-formly/ngx-formly/issues/1851#issuecomment-544483541

**Comment by ceszgdav** [comment]
> The value is handled by Angular through `[ngValue]` input, to get the expected value use `formControl.valueChanges` [#1851 (comment)](https://github.com/ngx-formly/ngx-formly/issues/1851#issuecomment-544483541)

Can you explainme how does this works? I'm trying to get the value of my dropdown because i'm getting some errors 
I don't know why i'm getting null to the first select if i  set defaultValue: "0" i get null to the first value

![image](https://user-images.githubusercontent.com/62302139/100477243-61031700-30ad-11eb-9aac-d38e2281609e.png)

and when i select some field this dont give me the true value
![image](https://user-images.githubusercontent.com/62302139/100477363-bb03dc80-30ad-11eb-8818-c6ec198160aa.png)
![image](https://user-images.githubusercontent.com/62302139/100477374-c35c1780-30ad-11eb-86d3-1387e14740e0.png)

**Comment by aitboudad** [comment]
@ceszgdav working from my side https://stackblitz.com/edit/angular-hpzxlq, we use the first option as `null` when passing the `placeholder`. I suggest using `hooks` instead of change callback to get the selected value:

```ts
    {
      key: 'name',
      hooks: {
        onInit: (field) => {
          return field.formControl.valueChanges
            .pipe(tap(value => { ... }));
        },
      },
    }
```
