### ISSUE TITLE
modelChange doesn't fire when FormyFieldConfig[] updated

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#2240]
We are using immutable with `(modelChanges)`. We have some dynamic fields that are created/removed when we change other form fields. When we replace the fields with a new list, the rendered form is updated correctly with the new fields but modelChanges does not fire. 

I understand that we are responsible for updating the FormGroup ourselves (until strict mode is released) but I had expected that modelChanges would still fire.

Is this a bug or is it the expected behaviour?

Thanks in advance.

**Comment by kenisteward** [comment]
@aitboudad will need to respond fully but I believe that is expected behavior. 

Your model technically did not change if you changed the fields. All that means is you have updated what is valid to be entered on the form. If one of those fields had a default value set then I believe it would fire because that new field configs added a value to the model

**Comment by freon27** [comment]
Ok, interesting, thanks :)

I think I've never quite grasped *exactly* the way that model, form and fields work together so it's sometimes not totally clear what controls what. In my head, model would be updated if fields were changed. Is this clearly documented anywhere? It's one of the areas I've struggled with.

**Comment by kenisteward** [comment]
In the docs it does say that modelchanges emits when the model value
updates. By that note, we can assume that if our changes do not cause the
model value to update then model changes should not emit.

So with default value, that would cause our model to change and we should
expect model changes to process. Adding a field that doesn't have a default
value does not change our model at all. So we should not expect model
changes to occur.  That goes the same for options updates or any other
firmly component @input

There may be a special circumstance where on initialization of the form it
doesn't emit model changes due to the model being passed in and the user
knowing of the model already but this I haven't tested.

Again this is my mental model so @aitboudad can confirm that I'm not
spouting nonsense :)

**Comment by aitboudad** [comment]
let say that was an expected behavior but with the `immutable` mode I see the need for emitting `modelChanges` in order to keep the model in sync.

**Comment by freon27** [comment]
So for now we would need to update both the model and the form manually if we change the list of fields?

**Comment by kenisteward** [comment]
To clarify, why do you need model changes event to occur when you update
the fields?  Is data not being bound to the new fields that you expect?

**Comment by freon27** [comment]
So essentially, we end up with a form control and a model value for a field that doesn’t exist any more when a field is removed. 

Our use case is that we have a multi-step form with a file input (that accepts multiple files) and a set of  fields that we have to supply for each file. The fields are dynamically updated  when the file input value changes, but the FormControls aren’t updated and there is no modelChange emitted.

**Comment by aitboudad** [comment]
well, I think you're talking about the `strict` mode, if so the better way, for now, is to init the form and model whenever the fields changes in order to have consistent behavior.

For multi-step make sure to use https://stackblitz.com/edit/angular-yu7bzv-uucyxg which may simplify handling your Form

**Comment by freon27** [comment]
Ok, that’s great, thanks :)

**Comment by aitboudad** [comment]
feel free to reopen if the issue still persists.
