### ISSUE TITLE
How can we engage?

### ISSUE THREAD

**Issue by mhamri** [ngx-formly/ngx-formly#2303]
**Question**
We decided to use ngx-formly in our project [revaedge.com ](revaedge.com) and instead of forking it thought we can engage and contribute to the main repo. My only concern is the release or PR speed and how fast we can have the codes back into the released version. 

what we are going to work on for now is full nebular components support. we can also discuss any other common point of interest that we can contribute to.

**Comment by aitboudad** [comment]
> We decided to use ngx-formly in our project revaedge.com 

:+1:

> forking it thought we can engage and contribute to the main repo

PR welcomed!

>  how fast we can have the codes back into the released version.

That depends on our availability but not more than ~2 weeks and for bug fixes ~1 week.

> what we are going to work on for now is full nebular components support

That's on our roadmap so that would be a good addition from your side :), for now, we may accept only the basic types ([ng-zorro-antd example](https://github.com/ngx-formly/ngx-formly/tree/main/src/ui/ng-zorro-antd)) to keep our codebase maintainable.
