### ISSUE TITLE
Json schema - map function - array children don't have form and formControl fields

### ISSUE THREAD

**Issue by piotr-kasprzik** [ngx-formly/ngx-formly#2482]
**Description**
Problem occurs in map function called with .toFieldConfig()
When schema contains field with type 'array', it children lack properties like 'form' or 'formControl'.

**Minimal Reproduction**
Go to [https://stackblitz.com/edit/angular-ppx9i3?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ppx9i3?file=src/app/app.component.ts) and check console. For simple types you can log 'form' field, in 'arrays' tab child fields return 'undefined' for that property

**Comment by Pietrex** [comment]
Unfortunately issue for me still exists, I would like to map fields directly, not traversing through array (parent) field every time.
I modified a little bit example, fields on the deepest level doesn't have fieldGroup property:
[https://stackblitz.com/edit/angular-ppx9i3-djief6](https://stackblitz.com/edit/angular-ppx9i3-djief6)

In our application we created custom field which value is used in select in the same form (dynamic enum properties). During schema interpretation phase we add handlers to those fields - we use 'form' property for that. It works for every scenario except arrays. I believe some solution is to check whether mapped field is type array, then looking down in fieldGroup if there are 'special' fields, but it will add some complexity when we will look for that in every mapper

**Comment by aitboudad** [comment]
> I modified a little bit example, fields on the deepest level doesn't have fieldGroup property:

not true, when an array type is empty, `fieldGroup` will be empty and the map fn will be called when adding a new item

**Comment by Adam-Michalski** [comment]
When element gets into mapFunction it has all properties which are required for Us, but this elements which are prepared for elements in array are missing them.
I have marked on this SS elements prepared for object which is element of array and other object which is not in array.

![image (3)](https://user-images.githubusercontent.com/5684123/92472242-7e74c300-f1d9-11ea-97c6-f6299e7047ec.png)

You can see that this which are created for array are missing many properties which gives US possibility to create dependent fields with dynamically loaded data, it is cause why we need to check every element here.

Also another issue with lack of this properties is when You add new element to array. We do not have straight connection to Array and looking in nested array for Our element is not optimal solution.

But later when I look inside array and its fieldGroup there are this elements with all properties which I think should be passed as mappedField to mapFunction but instead of them there are some others much skinnier.

![image (4)](https://user-images.githubusercontent.com/5684123/92472635-0d81db00-f1da-11ea-85fe-78b07ddee8aa.png)

Is this as it should be? Or this properties should be there from start?

Solution I see for now is to check every array and its every nested FormControl and do our logic but it would be not required if we would have acces for array element as it is for every other element passed as mappedField to mapFunction

**Comment by Pietrex** [comment]
@aitboudad may I ask for response? nested elements (second and next levels) don't have `fieldGroup` field on creation in map fn

**Comment by przemyslaw-k** [comment]
Dear @aitboudad problem still exists as provided in example by Adam-Michalski, are you planning to fix this issue?

**Comment by aitboudad** [comment]
Still not clear where the issue is and my comment is still valid https://github.com/ngx-formly/ngx-formly/issues/2482#issuecomment-687327293 I think :thinking:?

**Comment by aitboudad** [comment]
close in favor of https://github.com/ngx-formly/ngx-formly/issues/2809
