### ISSUE TITLE
Listen for select options change event in material custom template

### ISSUE THREAD

**Issue by davidcwuiyung** [ngx-formly/ngx-formly#2605]
**Question**

Is there any example that I can listen for to.options changes event in material custom template? The templateOptions.options gets set dynamically in parent component.

**Comment by aitboudad** [comment]
Rely on Observable option instead, so pass options as a `Subject` so when a change is made through `next` call you may be notified from the custom template by subscribing to the options.
Another solution is instead of set the options from the parent, the changes should be through a function instead `field.templateOptions.updateSelectOptions(options)`.
