### ISSUE TITLE
templateOptions json serialization problem

### ISSUE THREAD

**Issue by CanMehmetK** [ngx-formly/ngx-formly#2655]
When saving FormlyFieldConfig[] as json 
json is not valid (for mongodb persisting) becouse of  templateOptions.disabled  
`
 "expressionProperties": {
          "templateOptions.disabled": "!model.firstName"
        }
`

changing the "." seperator with something like "_" or "~" may be better

**Comment by aitboudad** [comment]
it seems MongoDB support passing dots in field names since `3.6` but not sure if that answers your needs,
For an alternative solution, you can use another separator in` Formly` by using a custom extension where you convert for example the dash sepator into a dot separator (to have an idea how to create a custom extension check our i18n example https://formly.dev/examples/advanced/i18n-alternative).

if you need help let me know!
