### ISSUE TITLE
Custom mat-datepicker header in ngxformly

### ISSUE THREAD

**Issue by shinde-prasad** [ngx-formly/ngx-formly#2814]
@aitboudad 
I am using mat-datepicker with custom header. Where I want to use (click) method events on next and previous button click. So that I want to get which is current month in the view when I click next and previous navigation. So how can I get that method response in json as a custom method in templateOptions:{}.

https://github.com/ngx-formly/ngx-formly/issues/2127#issuecomment-826261079

**Comment by aitboudad** [comment]
it should be added in `V6` instead, since `V5` supports Material >=v7 which doesn't that feature.

So I suggest creating a custom type that overrides the existing `datepicker` type until its `v6` is released.

https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/datepicker/src/datepicker.type.ts

**Comment by josem234** [comment]
@aitboudad 
I have follow your contributions in Angular Formly and I thank you for upgrading a tool I use.

There is an error where you call: (MatInput, <any>{ static: true })
It would be a pleasure to contact you.

**Comment by aitboudad** [comment]
@josem234 sure!
