### ISSUE TITLE
Migrating from formly to angular reactive forms

### ISSUE THREAD

**Issue by sometimesvlad** [ngx-formly/ngx-formly#2933]
Hi all! There was a need to migrate from formly to reactive forms when developing a large application, can formly offer any tools for this in close future? I'm not talking about all config files of project forms, for example, only custom formly controls, if possible, wrappers.

Best regards

**Comment by kenisteward** [comment]
I'm not exactly sure I understand the use case. Could you be more
specific?

Under the hood formly uses reactive forms and returns the form group so you
can use that.

If you meant storing formgroups as a string I don't think that can be done
due to their recursive structure in some instances

An example would be very helpful!

**Comment by aitboudad** [comment]
Formly use reactive forms under the hood as pointed above and to get access of its instance in `wrappers` for example check:
- form` property which is an instance of `FormGroup` that return the paren form instance
- `formControl` which returns the field control instance (`FormControl`).
