### ISSUE TITLE
Is there a best practice to catch errors from hideExpressions and other data-driven code?

### ISSUE THREAD

**Issue by pimarian** [ngx-formly/ngx-formly#2994]
**Question**

Hello.

We use JSON driven forms with `hideExpression`s. We are working on a feature that lets users create and edit forms. As they edit the JSON data structure, it is likely the content of `hideExpression` will result in syntax or reference errors when processed by ngx-formly. 

Is there existing support or best practice in ngx-formly to deal specifically with this type of error? For example an optional callback we could pass to run custom logic in case of error?

Alternatively we are thinking of replicating the `hideExpression` processing code and use it to validate the JSON data structure before sending it to ngx-formly.

Thank you

**Comment by kenisteward** [comment]
@pimarian Hi There!

I happen to be working on this same type of project internally!  Currently, my solution of this revolves around invoking a monaco-editor to allow users to create the expression as if they were using an IDE.  When they hit "check expression"  I'll take that expression parse it as a function and see if it has any type of errors.  If any appear I'll pop them in a "console-like" window under the monaco editor ( or the editor itself) and let them know what might be wrong with the expression.

In our wrapper library, whenever expressions are created, we create a wrapper function that adds try / catch around the expression and explicitly give errors based on the problem in the expression.  Before that, we just used the built-in Formly Expressions to let us know what expression had an error.

Let me know what you end up coming up with if this doesn't work for you!

**Comment by pimarian** [comment]
Thank you for explaining your approach @kenisteward 

> I'll take that expression parse it as a function and see if it has any type of errors

For this part, are you just creating a `Function` object? I believe that will handle any syntax error, but will not handle reference error, if you are using a local variables not passed by ngx-formly for example.

>  whenever expressions are created, we create a wrapper function that adds try / catch around the expression and explicitly give errors based on the problem in the expression

That is a good idea. What do you do in the catch block? Do you have something exposed in the global scope you call here to access the error?

**Comment by kenisteward** [comment]
> For this part, are you just creating a `Function` object? I believe that will handle any syntax error, but will not handle reference error, if you are using a local variables not passed by ngx-formly for example.

Exactly! We have an onInit / onPopulate function for an extension internally that we use to get the references to things like formControls / fields.  At that point, we take the string and convert it to a function that will wrap what we wanna pass to formly there.  I'll see if it is okay to expose this code from internal to give a better example of what I mean.

> That is a good idea. What do you do in the catch block? Do you have something exposed in the global scope you call here to access the error?

Same for above. Because we are running inside the lifecycle of formly we have access to all of formly's methods / objects / utilities AND closured reference to the service we create the formly fields with (which has our exception handling service injected) inside teh try catch is something like
```javascript

// if the expression is "hideExpression": "model.name !== 'kenisteward'; we convert that this way

const expressionWithLogic = `
      try {
          return ${currentlyProcessingFieldObj.hideExpression}
          } catch (e) {
               // not exactly what we call but something like it but this is where you can break e down to help the developer know what was wrong with the expression as we are  inside the function that is called by formly
    this.exceptionHandler.log(e);
    throw (e); 
          }
`
currentlyProcessingFieldObj.hideExpression = expressionWithLogic;
```

Couple of Notes:
1. we are actually creating a function internally and calling that function instead but this was a quicker way of getting the idea across.
2. this assumes that hideExpression is a string, if it is anything else then you'll use the function way that I just mentioned
3. This is all run onPopulate / oninit as well so we have access to fieldconfig if we need it.  So does the expression string because that is called directly by formly after we have reset it.

**Comment by pimarian** [comment]
Thanks, I did not realize the hideExpression function would have access to your injected service. That is great!

But, I don't understand something based on the code snippet above.
This is the function that processes `hideExpression` when it's a string in ngx-formly:

```javascript
export function evalStringExpression(expression: string, argNames: string[]) {
  try {
    return Function(...argNames, `return ${expression};`) as any;
  } catch (error) {
    console.error(error);
  }
}
```
If you preprocess the value as in your snippet, won't you get `return try { ... } catch (e) { ... };` as the body of the Function object? I don't think that is valid

**Comment by kenisteward** [comment]
I'll see if I can setup a stackblitz in the next couple days :)

**Comment by aitboudad** [comment]
By using a custom extension you may be able to catch those errors by wrapping expression properties, for an example check 18n example https://formly.dev/examples/advanced/i18n-alternative
