### ISSUE TITLE
how to write html code inside .ts component file in angular formly 

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#3021]
{
      template: `
        <div class="mt-2" *ngIf="imageFileName">
            <img [src]="model.image.value"  width="60px" height="60px" alt="">
        </div>
      `
    },

**Comment by aitboudad** [comment]
it's not possible due to Angular limitation on that part (require to use Angular compiler in browser),
so instead use one of the following solutions:

1- create a custom component type https://formly.dev/guide/custom-formly-field
2- use `expressionProperties`: https://github.com/ngx-formly/ngx-formly/issues/2057#issuecomment-579724475
3- use inline type (available in [v6](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.1)) https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-792260405
