### ISSUE TITLE
Json Schema powered formly: Getting cannot set properties of undefined error when we write model.somethingin expression properties for enum as datasource

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3088]
![image](https://user-images.githubusercontent.com/36687981/145150431-d14b1b54-72da-4d35-83ae-4e5546bd194e.png)

code:
 "multipleWithdrawalsPerDayAllowed": {
                      "type": "string",
                      "title": "ABC",
                      "enum": [
                        null,
                        "B",
                        "C"
                      ],
                      "widget": {
                        "formlyConfig": {
                          "expressionProperties": {
                            **"model.multipleWithdrawalsPerDayAllowed":**"field.parent.parent.model.pqr==='sachin'?null:model.multipleWithdrawalsPerDayAllowed",

**Comment by aitboudad** [comment]
The provided example is working as expected: https://stackblitz.com/edit/angular-q2hju2?file=src/app/app.component.ts, feel free to reopen if you've got a reproduction.

**Comment by coreConvention** [comment]
I am actually experiencing this exact same issue. Wondering if the original poster ever came up with a solution.

**Comment by aitboudad** [comment]
@coreConvention it could be related to one of theses situations:
- https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
- `model` is undefined which you can fix by setting  `defaultValue` to the field or simply use ternary operator (field.model?.foo) in the used expression.

**Comment by coreConvention** [comment]
Thanks for the response! I tried setting defaultValues on my fields, didn't seem to make a difference. Strangely enough the only thing that seemed to fix it was defining model like this in the markup:
[(model)]="model"

**Comment by aitboudad** [comment]
@coreConvention Formly only support `ReactiveFormsModule` so it hard for me to know the wrong part without a reproduction.

**Comment by coreConvention** [comment]
Yea it uses ReactiveFormsModule, which is why I thought it was weird that the two way binding fixed the issue. In any case, I'm not posting this here expecting resolution. Was just hoping the OP had figured out something else to resolve their issue.  I have tried to reproduce the issue in Stackblitz but a reproduction is damn near impossible with the code I am using this in because it uses an extremely complex series of steps to automate creation of widget properties in the json schema from several separate data-source/configurations with the schema and ui-schema stored separately as well, which them merges them together based on their path. The presets data in the model before its loaded into Formly. The net result is what appears to be a valid FormlyFieldConfig and model, but for whatever reason it only works with the two way binding.
