### ISSUE TITLE
Custom Formly Extension not applied when navigation to another component

### ISSUE THREAD

**Issue by preeteeg** [ngx-formly/ngx-formly#3111]
Hello i have implemented the following to mask some value using formly extension , this is working fine when you come on a component for the very first time, however when i navigate away to on another component or url it does not apply the masking anymore. Can someone help me on this issue. thank you for your response
````
 public onPopulate(field: FormlyFieldConfig): void {
        if (isAuthorisedField) {
          field.hooks = {
            ...(field.hooks || {}),
            onInit: (authorisedField: FormlyFieldConfig) => {
              authorisedField.formControl.setValue('XXX');
            }
        }
    }

**Comment by aitboudad** [comment]
Since the parent component is not destroyed by the router, there is no way for Formly to detect that event so I think it should be handled by your side by subscribing to the route event.

The solution may depends on the use-case, but if you want to apply it inside Formly Extension, just return an observable inside `onInit`:

```patch
if (isAuthorisedField) {
  field.hooks = {
    ...(field.hooks || {}),
    onInit: (authorisedField: FormlyFieldConfig) => {
+     return router.events.pipe(
+        tap(e => {
+         if(event instanceof NavigationStart) {
+           ...
+           authorisedField.formControl.setValue('XXX');
+         }
+       })
+     )
    }
}
```

**Comment by preeteeg** [comment]
thank you @aitboudad
