### ISSUE TITLE
Custom validation for array of objects

### ISSUE THREAD

**Issue by madhu23rima** [ngx-formly/ngx-formly#3174]
Is there a way to provide custom validation for array of objects. If yes, could you please provide an example.

In my use case I have an array like 
allocations : [ {fundName: 'abc', percentage: 10},{fundName: 'def', percentage: 30}]. I want to make sure that the percentage total of the array does not exceed 100. 

I have the validation for allocations defined as  "validators": {
        "validation": [
          {
            "name": "allocation-percent-total",
            "options": { "errorPath": "percentage" }
          }
        ]
      },

However the percent field is still being valid in case of an invalid scenario. Probably the "errorPath" value specified is not correct . How should be specify the error path for a property inside an array of objects

**Comment by aitboudad** [comment]
`errorPath` value here is wrong, you've multiple percentage fields inside array, two solution can be used:

1- Show the validation in the field array itself instead of percentage field (add https://github.com/ngx-formly/ngx-formly/issues/3170#issuecomment-1029762431 inside repeat field type)
2- pass the right key to `errorPath`:  ` { "errorPath": "0.percentage" }`

**Comment by madhu23rima** [comment]
Thank you
