### ISSUE TITLE
Formly seems to cache services injected into component instances

### ISSUE THREAD

**Issue by ng-commander** [ngx-formly/ngx-formly#3223]
**Description**
The creation life cycle of a FieldType component looks strange.
1. Constructor
2. ngOnDestroy
3. prePopulate
4. Constructor
5. ngOnInit

Furthermore seems Formly to cache services provided in FieldType based component instances.
The sample program shows when re-creating the same FieldType component with a new provided service:

1. the new service is used in the component instance, (Expected Behavior) 
2. the first (old) service instance is always used in the prePopulate method. (Unepected Behavior) 

**Minimal Reproduction**
https://stackblitz.com/edit/formly-prepopulate-provider-access-yzhmta
Show and hide Form-Field by pressing Toggle-Button produces relevant consol-logging.

**Your Environment**

- Angular version: 13.2.5
- Formly version: 6.0.0-next.8

**Comment by aitboudad** [comment]
I confirm that's an expected behavior due to the build step which is running in sync, the main purpose of the first created instance (which cached as well for future usage) is to be able to run field extension callbacks (`prePopulate` ...) during the build step where the field is not rendered yet.

The right solution is to support async build which we may give a try in the future.
