### ISSUE TITLE
|| operator not working with formly

### ISSUE THREAD

**Issue by prashantraj16** [ngx-formly/ngx-formly#3224]
'OR' operator not working in expressionproperties.
This is with || operator.

1. check check1.
2. uncheck check2.
3. type something in text1. check2 should get checked but it is not.
so the problem happens when check2 is manually unchecked.

https://stackblitz.com/edit/angular-ih6ugw-nchezv

**Comment by aitboudad** [comment]
We rely on a cached value to detect when to execute the expression but changing it would produce another issue which I'm not sure that would be a desired behavior.
The new behavior won't allow changing uncheck `check2` it would act as a read only because its value depends mainly on `check1` and `text1`.
