### ISSUE TITLE
Update formcontrol value from custom component

### ISSUE THREAD

**Issue by paragsaxena8** [ngx-formly/ngx-formly#3258]
Hello, 
I want to update the formControl value for the custom component I defined, where it returns data as an object.
as I go through documentation, it stats using `hooks` oninit will resolve the issue, but i want the output of form control from the custom component.

**Comment by aitboudad** [comment]
The request is not clear enough, there is a `formControl` property inside custom component so you just need to call `formControl.setValue` in order to set a new value and to know when the value is changed subscribe to `formControl.valueChanges`.
Use `hooks`  if you want an access of `formControl` through the field config:

```ts
{
  key: 'name',
  type: 'input',
  hooks: {
    onInit: field => field.formControl.valueChanges.pipe(
      ...
    )
  }
}
````
