### ISSUE TITLE
v6 adds an unnecessary (?) nested formly field and group

### ISSUE THREAD

**Issue by alfaproject** [ngx-formly/ngx-formly#3267]
I'm trying to upgrade a rather large project to v6 and noticed that the new version adds an extra formly-field and formly-group which wasn't there in v5:
<img width="955" alt="Screenshot+2022-04-12+at+17 03 29" src="https://user-images.githubusercontent.com/60164/163005924-46fbf520-ad3e-4a13-889f-e9df2254c298.png">

I'm not sure if this is on purpose and if it is, is there any explanation why? We are a bit picky with the number of DOM elements that our apps create in the browser and this caught our attention.

**Comment by aitboudad** [comment]
That's an expected feature which allows managing the root field within `field-group` type, so that gives you more control over Formly internal structure.

So to adjust the style of Formly root field you may need to update the css selector into: 
```patch
- formly-form {
+ formly-form > formly-field {
}
```

Also we've introduced a new option which eliminate `<formly-field>`: https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-804500185

I think we need to mention this info in the upgrade file, so will keep this issue open till added.

**Comment by alfaproject** [comment]
So the extra `formly-group` nested in that `formly-field` is also expected?

With our current version (v5.10) we have:
```html
<formly-form>
  <formly-field>
    <formly-wrapper-mat-form-field>
    ...
```

The new v6 produces this without any configuration changes:
```html
<formly-form>
  <formly-field>
    <formly-group> <!-- this and the wrapper field are new !>
      <formly-field>
        <formly-wrapper-mat-form-field>
        ...
```

**Comment by aitboudad** [comment]
> So the extra `formly-group` nested in that `formly-field` is also expected?

yes, I've missed that one.

**Comment by alfaproject** [comment]
Alright, I'll give a try using that new flag and without it and give some feedback if I have any to give. Thank you for your support
