### ISSUE TITLE
focus: true does not work on ionic

### ISSUE THREAD

**Issue by dolphinigle** [ngx-formly/ngx-formly#3299]
**Description**
The [focus](https://github.com/ngx-formly/ngx-formly/blob/05891dff4e4589d48c17d89dfc003241e77e4618/src/core/src/lib/models/fieldconfig.ts#L146) property on fields does not work on ionic.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-ionic-dpc1gj?file=app/app.component.html

**Your Environment**

- Angular version: 13.0.0
- Formly version: 6.0.0-next.7

**Additional context**
It seems to be a regression of #1374

Looking around the code, i can't find anywhere in the current code where ion input's [setFocus](https://ionicframework.com/docs/api/input#setfocus) is called. Previously, it was called [here](https://github.com/ngx-formly/ngx-formly/pull/1442/files#diff-0d6b219a469afebc37903bb205d33c69804b328360f6d84a79938535ca31824cR29)

Thank you for the fantastic library!

**Comment by aitboudad** [comment]
> Looking around the code, i can't find anywhere in the current code where ion input's [setFocus](https://ionicframework.com/docs/api/input#setfocus) is called. Previously, it was called [here](https://github.com/ngx-formly/ngx-formly/pull/1442/files#diff-0d6b219a469afebc37903bb205d33c69804b328360f6d84a79938535ca31824cR29)

We use [ionFocus](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/ionic/form-field/src/formly.attributes.ts#L8) instead of `setFocus`

**Comment by aitboudad** [comment]
I've tried with `setFocus` but it doesn't seems working as well and the issue seems related to https://github.com/ionic-team/ionic-framework/issues/24009 or https://github.com/ionic-team/ionic-framework/issues/18132 hope it'll be fixed soon.

Here a reproduction example which doesn't use Formly: https://stackblitz.com/edit/ionic6-angular13-14qu5a?file=src/app/app.component.html
