### ISSUE TITLE
Is it possible to use a Formly extension only with a specific form?

### ISSUE THREAD

**Issue by tzehetner** [ngx-formly/ngx-formly#3338]
I have some logic that I want to apply to all fields of a form. I thought I could write an extension, but it seems like extensions are always applied to all forms of an application. Is there a way to limit extensions to specific forms? Or is there some other mechanism to apply initializations to all fields of a form.

**Comment by MaxKless** [comment]
Yes, extensions are always applied to all forms. 
You could try to register an extension using `FormlyModule.forChild` in the component's module so that it will only apply to formly forms in that module - this is the closest you will get to defining a local extension, I think.

You can also use the `hooks` feature to execute logic on init. Check out this egghead.io video by @juristr: https://egghead.io/lessons/angular-add-functionality-to-angular-formly-controls-with-formly-lifecycle-hooks

**Comment by tzehetner** [comment]
Both solutions don't work for me. I don't want to add the same hook to every field and FormlyModule.forChild in a sub-module still seems to add the extension globally.

**Comment by tzehetner** [comment]
Thanks, yes, I already wrote a helper function for that. In case anybody else needs it:

```ts
/** Invokes a function recursively for the specified fields and their descendants. */
export function forEachFormlyField(fields: FormlyFieldConfig[], action: (field: FormlyFieldConfig) => void) {
  for (const field of fields) {
    //Invoke action for current field

    action(field);

    //Process child fields

    if (field.fieldGroup) {
      forEachFormlyField(field.fieldGroup, action);
    }

    if (field.fieldArray) {
      forEachFormlyField([field.fieldArray], action);
    }
  }
}
```
