### ISSUE TITLE
fieldArray now accessible via a method, but how to modify fields inside fieldArray?

### ISSUE THREAD

**Issue by ajojra** [ngx-formly/ngx-formly#3351]
![image](https://user-images.githubusercontent.com/18018657/173537205-aa5a1049-6d7b-4215-803a-e6de2a696749.png)
I have noticed that fieldArray changed from a 'get' accessor to a method from v6.0.0-next.1 to v6.0.0-next.9. This made impossible to modify the fields inside fieldArray.

I generate schema at API side, intercept schema and modify the fields inside before inserting into formly-form.

What's best option now for me?

**Comment by kenisteward** [comment]
@ajojra 
2 possible workarounds

1. The Jason schema function allows passing of a map function in order to change fields before getting finally set.  Making the assumption you are using that module from where the field array function is set.

2. When you parse the fields and find field arrays call the function get those immediate fields and make changes as needed


@aitboudad was that change made for performance sake? They started out as I think just a base field then migrated to getter and now a function.

**Comment by ajojra** [comment]
Thank you @kenisteward.
**workaround 1** - still gives fieldArray, hence can't modify:
![image](https://user-images.githubusercontent.com/18018657/173719991-d76373c1-40fd-47dd-abc6-19692fdfa8ca.png)

**workaround 2** - I've called the function to get fieldArray, but changes on that fieldArray doesn't reflect on form. eg: if I inject hooks there, it won't get passed on to form.

**Comment by kenisteward** [comment]
Do you happen to have a stack blitz handy?

**Comment by ajojra** [comment]
I have noticed, this map function executes for each field in schema. 

This makes it very difficult to pin point field in an array to modify.

**Comment by ajojra** [comment]
don't have stackblitz yet, I'll create one now.

**Comment by kenisteward** [comment]
> Here we go: https://stackblitz.com/edit/angular-u3aupq?file=src/app/app.component.ts
> 
> just trying to run this console: `console.log('field initiated');`

I'll give it a whirl when I can get to a laptop thanks for setting it up

**Comment by ajojra** [comment]
Thanks mate, this is simple implementation. My use case is deeply nested schema though. I access fields from schema via fieldArray and update it's hooks/templateOptions asynchronously.

**Comment by kenisteward** [comment]
@ajojra 

Have it working here.  you just have to return a function that returns the changes to what you wanted in it

https://stackblitz.com/edit/angular-u3aupq-wttsb6?file=src%2Fapp%2Fapp.component.ts

**Comment by ajojra** [comment]
interesting.. let me try this. Thanks a heaps for quickly picking it up.

**Comment by ajojra** [comment]
> @ajojra
> 
> Have it working here. you just have to return a function that returns the changes to what you wanted in it
> 
> https://stackblitz.com/edit/angular-u3aupq-wttsb6?file=src%2Fapp%2Fapp.component.ts
> 
> basically the same thing you have to do when it got turned into a getter (which was redefine it with object.define)

That's a bit tricky way when I have such a complex deeply nested (arrays inside arrays) form. Didn't notice any performance issue with `fieldArray` being a getter.

**Comment by kenisteward** [comment]
@ajojra 
2 possible workarounds

1. The Jason schema function allows passing of a map function in order to change fields before getting finally set.  Making the assumption you are using that module from where the field array function is set.

2. When you parse the fields and find field arrays call the function get those immediate fields and make changes as needed


@aitboudad was that change made for performance sake? They started out as I think just a base field then migrated to getter and now a function. 
    @ajojra it would then be much easier to use the map function and do what I did outside of it instead in there. You have bothe  the schema that is being converted and what it is currently being converted to.

Lemme know if that doesn't work.

**Comment by kenisteward** [comment]
@ajojra it would then be much easier to use the map function and do what I did outside of it instead in there. You have bothe  the schema that is being converted and what it is currently being converted to.

Lemme know if that doesn't work.

**Comment by ajojra** [comment]
found another way, synchronous one to handle it, and seems work perfect for my requirements:
https://stackblitz.com/edit/angular-u3aupq-7pj74e?file=src/app/app.component.ts

hope I am not breaking anything internal.

**Comment by kenisteward** [comment]
That looks like the shorthand way of how I suggested which is good! Glad it works for ya.

**Comment by aitboudad** [comment]
The main purpose of using method is to simplify customizing the generated config so in order to do that just follow the following solution:

```ts
const getFieldArrayItem = field.fieldArray;
field.fieldArray = (root) => {
  const item = getFieldArrayItem(root);
  // edit item
  // ...

  return item;
}
```
