### ISSUE TITLE
Angular v15: Add support of MatLegacyFormFieldModule

### ISSUE THREAD

**Issue by iKrishnaSahu** [ngx-formly/ngx-formly#3494]
Is there any plan to support MatLegacyFormFieldModule of angular v15?

Angular is going to release v15 where it brings mdc components for all the existing component and moved old components as legacy components. We have done stylings for old components as we do not have enough capacity to styles latest mdc components.

Currently the styles are breaking for us as by default mdc is getting used internally for dynamically generated form fields.

Do you guys have any plan for v15 migration of this repo?

**Comment by iKrishnaSahu** [comment]
@aitboudad do you guys have any timeline for the same?

**Comment by aitboudad** [comment]
> do you guys have any timeline for the same?

No

**Comment by jackcw** [comment]
I started having a look into how the upgrade process of ngx-formly to v15 would be. I might have some capacity to do the upgrade work @aitboudad. I wanted to check on the feasibility of me doing this upgrade work first. It looks like all the dependencies would need to be upgraded to angular v15. I would duplicate the material ui library and name it as material-legacy and upgrade the material library to the new implementation. I did some of the upgrade to see what happened and it definitely breaks a lot of tests across the other ui libraries doing the upgrade aswell due to upgrade angular. Do you have any work in the pipeline that would be affected?

**Comment by aitboudad** [comment]
@jackcw is it possible to keep supporting angular v14? My plan is to keep the current base compatible with both versions: v14 and v15 (if possible of course), for legacy components they can added with `legacy` suffix (for example: `src/ui/material)/input-legacy`)

**Comment by jackcw** [comment]
I looked into material 15 and it said you can't use new material and old material in the same module which is why I thought putting it into its own ui library might work well so that when you setup formly in your project you install either material or material legacy. It would also make the upgrade path a bit less painful as you could just swap out your imports for material to material-legacy and it will all continue to work.

I would have to look into angular 14 compatibility once upgraded. I don't tend to do any publishable libraries work where I would need to use different angular versions

**Comment by aitboudad** [comment]
Just tested the current Formly v6 with Angular v15 and it seems working without any issue: https://stackblitz.com/edit/angular-xvuzyo,
Based on that, I think `material-legacy` is a good suggestion!

**Comment by jackcw** [comment]
I'll have a go at it tomorrow / this week and push up a PR to see how it's all working. Focus on getting it all working first then look into the tests

**Comment by jackcw** [comment]
Hi @aitboudad i've started the work to migrate to angular 15 with the material update. [Here's the branch on my fork](https://github.com/jcw-os/ngx-formly/tree/feat/ng-update-15). 

Few things of note that have changed in v15 of angular material:

- Legacy mode has been removed and so the look of material will have changed, i add the outline as the default appearance for the demo app but the user will set it to their preferred appearance as normal.

- There has been an update to the way that [suffix and prefix work](https://github.com/angular/components/blob/main/guides/v15-mdc-migration.md#form-field)

> While the previous form-field had a single directive for prefixes (matPrefix) and a single directive for suffixes (matSuffix), the MDC-based form-field distinguishes between text prefix/suffixes which are baseline aligned with the input text, and icon prefix/suffixes which are center aligned in the form-field. Use matTextPrefix or matTextSuffix to indicate a text prefix/suffix, and matIconPrefix or matIconSuffix to indicate an icon prefix/suffix. The old matSuffix and matPrefix APIs will behave like icons, though they are now deprecated.

I havent updated this just yet but i have had to replace the ng-container for the matPrefix/matSuffix - `src/ui/material/form-field/src/form-field.wrapper.ts` because of an error where material tries to call hasAtrribute on the element

**Slider**
This was probably the most reworked component 

- renamed `thumbLabel` to `discrete` i have changed this in the component attributes but left the props with the key of thumbLabel. Probably the best solution is to add discrete and put a deprecated label on that param and allow people to slowly move across.
- The slider now has range capacity i would probably implement this as a new type as the model would be very different. Probably call it slider-range

I will get the material-legacy piece setup. Currently i have just copied the folder after upgrading to v15 so its there untouched. Also i've not looked at the tests just yet

**Comment by aitboudad** [comment]
@jackcw Many thanks! Please just send a PR, I'll try to check it further and make a release (this week) if everything went well.

**Comment by jackcw** [comment]
Will do @aitboudad i've got the material legacy working now as well

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by dkimmich-onventis** [comment]
@aitboudad I don't see a possibility to use the Legacy Material Modules with the newly released formly v6.1.0, am I missing something?
