### ISSUE TITLE
expressions function not working for anything other than model properties in ngx-formly 6

### ISSUE THREAD

**Issue by siovene** [ngx-formly/ngx-formly#3518]
**Description**
Using `expressions` does not work anymore for functions, while still working for model properties. E.g.:

```
expressions: {
  'props.disabled': "model.someKey === 'someValue'"
}
```

The one above works fine.

```
expressions: {
  'props.disabled': () => this.someObjectProperty
}
```

The one above doesn't work (also for primitive types. The first value is recognized, but when `this.someObjectProperty` is updated, the expression is not evaluated again.

**Minimal Reproduction**
https://stackblitz.com/edit/formly-starter-example-7fcqpt?file=src/app/app.component.ts

**Your Environment**
- Angular version: 15
- Formly version: 6

**Additional context**
This was working on Formly 5.

Thanks!

**Comment by aitboudad** [comment]
Please check the upgrade guide https://formly.dev/docs/guide/migration, I think the issue is related to this feature https://formly.dev/docs/guide/migration#4-checkexpressionon-is-set-to-modelchange-by-default which is changed in v6.

To solve the issue use one of the following solution:
- set `checkExpressionOn` to `changeDetectionCheck`:
```patch
FormlyModule.forRoot({
+ extras: {
+   checkExpressionOn: 'changeDetectionCheck',
+ },
}),
```
- pass an observable object to expression
- manually call detect changes: `this.options.detectChanges(this.fields[1]);`

**Comment by siovene** [comment]
Thanks, ultimately I solved my issue by refactoring my code to use `options.formState` to store information that I needed to watch in `expressions`.
