### ISSUE TITLE
Migration for "DefaultValue for fieldGroup and fieldArray type" does not compile

### ISSUE THREAD

**Issue by gkamperis** [ngx-formly/ngx-formly#3660]
The code shown in the link below does not compile with a TS error as the `name` property is missing.

https://formly.dev/docs/guide/migration#2-defaultvalue-for-fieldgroup-and-fieldarray-type

**Your Environment**

- Formly version: 6.1.3

**Comment by aitboudad** [comment]
Hi, the issue is not clear. could you please elaborate and provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Please feel free to leave a comment once you've a got a reproduction example so we can check it further on our side and provide a fixed if needed.

Thank you!

**Comment by gkamperis** [comment]
@aitboudad did you try the code of the documentation link in your starter example?

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-v86x9u?file=src%2Fapp%2Fapp.module.ts

![image](https://user-images.githubusercontent.com/18055519/235539823-723283e1-7297-4820-9b74-d08d44048571.png)

**Comment by aitboudad** [comment]
I see, updated the upgrade. Use `name` instead of `extends`:

```patch
{
+ name: 'formly-group',
- extends: 'formly-group',
  defaultOptions: {
    defaultValue: {},
  },
},
```

Thank you!
