### ISSUE TITLE
Hide expression(string): conditional rendering 

### ISSUE THREAD

**Issue by jljohnson001** [ngx-formly/ngx-formly#3755]
**Description**
When using string on hide expression the following does not evaluate as expected:
<ins>Multiple conditions using not equal to</ins>
`hide: "field.model.country !== 'USA' || field.model.country !== 'UK'"`

Note that the expression evaluates as expected in the following scenarios:
<ins>Single condition using not equal to</ins> 
`hide: "field.model.country !== 'USA'"`
<ins>Multiple conditions using equal to</ins>
`hide: "field.model.country === 'USA' || field.model.country === 'UK'"`

**Minimal Reproduction**
https://stackblitz.com/edit/angular-yobrug-bc5zv3?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: ^14.0.0
- Formly version: ^6.0.0

**Additional context**

**Comment by DavWe** [comment]
The hide expression is working correctly. The expression `hide: "field.model.country !== 'USA' || field.model.country !== 'UK'"` always evaluates to true, because every string is not equal to 'USA' OR not equal to 'UK'. 

| field.model.country | field.model.country !== 'USA' \|\| field.model.country !== 'UK' |
| --- | --- |
| USA | true |
| UK | true |
| fizz | true |

This expression `hide: "field.model.country !== 'USA' && field.model.country !== 'UK'"` is probably what you want.
