### ISSUE TITLE
props.required expressions not working correctly

### ISSUE THREAD

**Issue by craigsh** [ngx-formly/ngx-formly#3756]
**Description**
Using an expression for props.required on multiple fields leaves the form invalid when fields are no longer required.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-x2hul5

**Your Environment**

- Angular version: 16.1.5
- Formly version: 6.1.8

**Additional context**
I have a requirement for multiple text fields to be required if any one of them has content. So I added a props.required expression which checks the model for content in the other fields.

I'm using Angular Material, and it correctly removes the * required indicator from the field labels when they are no longer required, but the form state still shows as INVALID.

**Comment by vniacsta** [comment]
I have the same issue! 
@craigsh did you find any working solution/alternative?

**Comment by craigsh** [comment]
@vniacsta no, I'm just ignoring it for now, hoping it will get fixed in a future release. It's a low priority bug for me.

**Comment by vniacsta** [comment]
In my template, I hide several fields depending on the model. The same key will be used if the field has some differences. In this case, is the props.required. I guess the issue is the key being duplicated. 

I basically checked for duplicated keys with different required values. Then on hooks onInit, using fieldChanges and a filter from rxjs, I check if it’s type ‘hidden’ and value false. The main verification is to check if the field.key exists in my duplicated set and if field.hide is false. 
With that return, I can clear validators or set validators depending on the original props.required value. 

It’s a hell of a workaround. But it works in my case. I hope it helps you too @craigsh.

**Comment by FritzHerbers** [comment]
Initially text1 and text2 are undefined: required=false
After you enter data, text1 = 'somedata': required=true
When you empty text1, text1 = '' (it is not undefined or null as before): required still = true
But when you use !!text1: required = false

change to `'props.required': '!!model.text1'`

https://stackblitz.com/edit/angular-x2hul5-zijg7p

**Comment by aitboudad** [comment]
**Note**: In [v6.2.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.2.0), we added a warning log when passing an invalid type to `required` property.
