### ISSUE TITLE
Cannot get updated field value when field in different formgroup.

### ISSUE THREAD

**Issue by wyxcoder** [ngx-formly/ngx-formly#3788]
**Question**

A clear and concise description of what the question is.

Like [in this code](https://stackblitz.com/edit/angular-ntyh6k?file=src%2Fapp%2Fcustom-field.type.ts) 
 I have total six amount buttons with same key. Each has different value. When you click one, the value will be stored in model and in turn highlight that button. But I found one of the bottom three buttons could be highlighted together with one of the top three buttons. Like screenshot below, any clue?  I think it is related to the formgroup.

![image](https://github.com/ngx-formly/ngx-formly/assets/47443766/80817bfb-0837-4de0-a7a0-1c039a717854)

**Comment by HazizKhan** [comment]
Hi, @wyxcoder I believe this issue is not related to the as your custom formly field is not input type.
In my understanding you have a custom field which is not input so you cannot use [formControl] directive for forms so for the component it will be difficult to detect changes.
You might want to detect the changes inside your custom field component manually by subscribing on the valueChanges of the form control.
```import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FieldType, FormlyFieldConfig } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-inputButton',
  template: `
    <div>
      <button type="button" class="btn btn-primary btn-md btn-u-primary" [class]="{ active: (model[field.key+'']==field.defaultValue), disabled: props.disabled }"
       (click)="setValue()">{{props.label}}</button>
    </div>
  `,
})
export class FormlyFieldInputButton extends FieldType implements OnInit {
  constructor(private changeDetectorRef: ChangeDetectorRef) {
    super();
  }
  ngOnInit() {
    this.field.formControl.valueChanges.subscribe(() => {
      this.changeDetectorRef.detectChanges();
    });
  }
  setValue() {
    this.field.formControl.setValue(this.field.defaultValue);
  }
  isValid(field: FormlyFieldConfig): boolean {
    if (field.key && field.formControl) {
      return field.formControl.valid;
    }

    return field.fieldGroup
      ? field.fieldGroup.every((f) => this.isValid(f))
      : true;
  }
}
```
here you can find the example: https://stackblitz.com/edit/angular-ntyh6k-tv6uxc?file=src%2Fapp%2Fcustom-field.type.ts
