### ISSUE TITLE
Make application bundle smaller using Angular v17 APIs

### ISSUE THREAD

**Issue by k3nsei** [ngx-formly/ngx-formly#3844]
**Is your feature request related to a problem? Please describe.**
Formly is taking a big chunk of my application bundle.

**Describe the solution you'd like**
Mayby with newest features that Angular V17 gives we can make field types lazy using `dynamic imports`, `NgComponentOutlet` and `@defer`. 

**Describe alternatives you've considered**
I can write dummy shells for field type components and use `@defer` inside to lazily load real component, but it's complex and time consuming task.

**Additional context**
None.

**Comment by aitboudad** [comment]
Hi, could you please check the following solution: https://github.com/ngx-formly/ngx-formly/issues/3064#issuecomment-1179810546 ?

**Comment by k3nsei** [comment]
@aitboudad We are not using NgModules anymore. We shifted to standalone APIs and build-in control flow. I think it's time to modernize also Formly.

**Comment by aitboudad** [comment]
I agree, I may see first if we can provide support of standalone  Api with the current version else  we'll try to provide it in v7.

**Comment by k3nsei** [comment]
I think v7 would be nice because compatibility problems of Angular v13. As standalone API's where introduced in Angular v14.

**Comment by json-derulo** [comment]
Apart from possibly dropping support for old Angular versions, the standalone migration should work in a backwards compatible way. Instead of declaring and exporting the components and directives in the modules, they can be imported and exported. A new project can directly work with the components & directives, while existing projects can continue to use the modules. Angular Material recently re-worked their code base in this way. See also: https://angular.io/guide/standalone-components#standalone-components-for-library-authors

**Comment by k3nsei** [comment]
For example my whole application and things on top of Formly that we build are using standalone APIs. But we cannot do anything about Formly Core which is reason of bloated 2mb bundle in our case.

**Comment by nthonymiller** [comment]
IMO v7 should bump the minimum Angular to 17 and support standalone api. Maybe a RFC could be started to for v7.

**Comment by k3nsei** [comment]
In Angular v18 there will be even more breaking changes like new change observables for status, pristine, dirty etc. So it would be hard and super limiting to avoid introducing them also here. Especially that there is also angular material v3 migration coming.
